openapi: 3.0.0

info:
  title: blue bird flashcards API
  version: 1.0

paths:
  /user/{userName}:
    get:
      summary: Returns bluebird user information
      parameters:
        - in: path
          name: userName
          schema:
            type: string
          required: true
          description: userName
      responses:
        "200":
          description: OK
        "400":
          description: The specified user ID is invalid.
        "500":
          description: Bad request.
        default:
          description: Unexpected error.
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:{{Region}}:lambda:path/2015-03-31/functions/arn:aws:lambda:{{Region}}:{{Account}}:function:bluebird-get-user/invocations"
        credentials: "arn:aws:iam::{{Account}}:role/bluebird-gateway-role"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

  /collection/{collectionId}:
    get:
      summary: Returns a list of collections by user
      parameters:
        - in: path
          name: collectionId
          schema:
            type: string
          required: true
          description: composed by user and collectionName
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collection'
        "400":
          description: The specified user ID is invalid.
        "500":
          description: Bad request.
        default:
          description: Unexpected error.
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:{{Region}}:lambda:path/2015-03-31/functions/arn:aws:lambda:{{Region}}:{{Account}}:function:bluebird-get-collection/invocations"
        credentials: "arn:aws:iam::{{Account}}:role/bluebird-gateway-role"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

  /collection:
    put:
      summary: saves or replaces a list of collections
      responses:
        "200":
          description: OK
        "400":
          description: The specified user ID is invalid.
        "500":
          description: Bad request.
        default:
          description: Unexpected error.
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:{{Region}}:lambda:path/2015-03-31/functions/arn:aws:lambda:{{Region}}:{{Account}}:function:bluebird-put-collection/invocations"
        credentials: "arn:aws:iam::{{Account}}:role/bluebird-gateway-role"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

components:
  schemas:
    Collection:
      type: object
      properties:
        collectionId:
          type: string
        name:
          type: string
        owner:
          type: string
      required:
        - collectionId
        - name
