AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: bluebird infrastructure

Parameters:
  DeploymentBucket:
    Type: String
    Description: The name of the S3 bucket in which packaged code is stored
  StageName:
    Type: String
    Description: Current Stage
    Default: dev

Globals:
  Function:
    Timeout: 3

Resources:
  BluebirdAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: bluebird-api
      DefinitionUri: swaggerSpec.yaml
      StageName:
        Ref: StageName

  GetCollections:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bluebird-get-collections
      Runtime: nodejs8.10
      Handler: collections.get
      CodeUri: app/
      Events:
        GetCollectionsAPI:
          Type: Api
          Properties:
            RestApiId: !Ref "BluebirdAPI"
            Path: /collections
            Method: GET
