AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: bluebird infrastructure

Parameters:
  DeploymentBucket:
    Type: String
    Description: The name of the S3 bucket in which packaged code is stored
  StageName:
    Type: String
    Description: Current Stage
    Default: dev

Globals:
  Function:
    Timeout: 3

Resources:
  BluebirdAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: bluebird-api
      DefinitionUri: swaggerSpec.yaml
      StageName:
        Ref: StageName

  CollectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bluebird-collections
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      AttributeDefinitions: 
        - 
          AttributeName: "collectionId"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "collectionId"
          KeyType: "HASH"

  GetCollections:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bluebird-get-collection
      Runtime: nodejs8.10
      Handler: collections.get
      CodeUri: build
      Environment:
        Variables:
          COLLECTIONS_TABLE: !Ref CollectionsTable
      Events:
        GetCollectionAPI:
          Type: Api
          Properties:
            RestApiId: !Ref "BluebirdAPI"
            Path: /collections
            Method: GET

  PutCollections:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bluebird-put-collection
      Runtime: nodejs8.10
      Handler: collections.put
      CodeUri: build
      Environment:
        Variables:
          COLLECTIONS_TABLE: !Ref CollectionsTable
      Events:
        PutCollectionsAPI:
          Type: Api
          Properties:
            RestApiId: !Ref "BluebirdAPI"
            Path: /collections
            Method: PUT
